repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Using a recent, stable version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0 # Using a recent, stable version
    hooks:
      - id: flake8
